version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:80" 
    volumes:
      - .:/var/www/html
    environment:
      - DB_HOST=db
      - DB_DATABASE=casino
      - DB_USERNAME=root
      - DB_PASSWORD=
    depends_on:
      - db
  db:
    image: mysql:5.7
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: casino
      MYSQL_ROOT_PASSWORD: 
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
